export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';
export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';

export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';
export const FETCH_CITY_REQUEST = 'FETCH_CITY_REQUEST';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_FAILURE = 'FETCH_CITY_FAILURE';

export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';
export const FETCH_PLACE_REQUEST = 'FETCH_PLACE_REQUEST';
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS';
export const FETCH_PLACE_FAILURE = 'FETCH_PLACE_FAILURE';

export const FILTER_CITY_PLACES_CHANGE = 'FILTER_CITY_PLACES_CHANGE';

export type Types = typeof FETCH_COUNTRIES_REQUEST |
  typeof FETCH_COUNTRIES_SUCCESS |
  typeof FETCH_COUNTRIES_FAILURE |
  typeof FETCH_COUNTRY_REQUEST |
  typeof FETCH_COUNTRY_SUCCESS |
  typeof FETCH_COUNTRY_FAILURE |
  typeof FETCH_CITIES_REQUEST |
  typeof FETCH_CITIES_SUCCESS |
  typeof FETCH_CITIES_FAILURE |
  typeof FETCH_CITY_REQUEST |
  typeof FETCH_CITY_SUCCESS |
  typeof FETCH_CITY_FAILURE |
  typeof FETCH_PLACES_REQUEST |
  typeof FETCH_PLACES_SUCCESS |
  typeof FETCH_PLACES_FAILURE |
  typeof FETCH_PLACE_REQUEST |
  typeof FETCH_PLACE_SUCCESS |
  typeof FETCH_PLACE_FAILURE |
  typeof FILTER_CITY_PLACES_CHANGE;
